Dockerfile updated for ubuntu.
This is also potentially a dead end.  Shows similar problems

diff --git a/assets/initial-wrapper b/assets/initial-wrapper
--- a/assets/initial-wrapper
+++ b/assets/initial-wrapper
@@ -118,17 +118,21 @@ gitlab-ctl reconfigure
 echo "SCANNING DIR"
 ls -A /var/opt/gitlab
 
-# # Make sure PostgreSQL is at the latest version.
-# # If it fails, print a message with a workaround and exit
-# if [ "${GITLAB_SKIP_PG_UPGRADE}" != true ]; then
-#     gitlab-ctl pg-upgrade -w || failed_pg_upgrade
-# fi
+echo "upgrading pg.. "
+# Make sure PostgreSQL is at the latest version.
+# If it fails, print a message with a workaround and exit
+if [ "${GITLAB_SKIP_PG_UPGRADE}" != true ]; then
+    gitlab-ctl pg-upgrade -w || failed_pg_upgrade
+fi
 
-gitlab-ctl reset-grafana
+# apparently this command is no longer available and results in a "I don't know that command"
+# gitlab-ctl reset-grafana
 
+echo "postconfigure"
 if [ -n "${GITLAB_POST_RECONFIGURE_SCRIPT+x}" ]; then
   echo "Running Post Reconfigure Script..."
   eval "${GITLAB_POST_RECONFIGURE_SCRIPT}"
 fi
 
+echo "stopping gitlab"
 gitlab-ctl stop
